version: v0.7.1-alpha.1

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/

    cors:
      enabled: true

      allowed_origins:
        - http://127.0.0.1:4200

      allowed_methods:
        - POST

        - GET

        - PUT

        - PATCH

        - DELETE

      allowed_headers:
        - Authorization

        - Cookie

        - Content-Type

        - X-CSRF-Token

      exposed_headers:
        - Access-Control-Allow-Origin

        - Access-Control-Allow-Credentials

        - Content-Type

        - Set-Cookie

      allow_credentials: true

  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4200/

  allowed_return_urls:
    - http://127.0.0.1:4200

  methods:
    password:
      enabled: true
    link:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4200/error

    settings:
      ui_url: http://127.0.0.1:4200/settings

      privileged_session_max_age: 15m

    recovery:
      enabled: true

      ui_url: http://127.0.0.1:4200/settings

    verification:
      enabled: true

      ui_url: http://127.0.0.1:4200/verification

      after:
        default_browser_return_url: http://127.0.0.1:4200/email-verify

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4200/sign-in

    login:
      ui_url: http://127.0.0.1:4200/sign-in

      lifespan: 10m

    registration:
      lifespan: 10m

      ui_url: http://127.0.0.1:4200/registration

log:
  level: debug

  format: text

  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt

  bcrypt:
    cost: 8

identity:
  default_schema_id: default

  schemas:
    - id: default

      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtp://55cc17f0ede63d:e07b6838d19dea@smtp.mailtrap.io:587

    from_address: "test@gmail.com"

    from_name: "Live"

session:
  lifespan: 4380h00m00s
